USE [master]
GO
declare @db varchar(20)
/* ====================================================================================================
 Author:		xxx
 CreateDate:	2020-08-20
 Description:	Erstellen der Datenbank ohne DROP, damit diese nicht versehentlich gelöscht wird. 
				Eingetragen werden muss manuell
				- Name der Datenbank
				- mde + mdf mit Pfad und Datenbank
 History
 2020-08-20	dj	erstellt und gestestet
 ====================================================================================================*/
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Zimmersport')
BEGIN
	CREATE DATABASE [Zimmersport]  CONTAINMENT = NONE ON  PRIMARY ( 
		NAME = N'Zimmersport', FILENAME = N'D:\DB\Zimmersport.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB 
	)
	LOG ON ( 
		NAME = N'Zimmersport_log', FILENAME = N'D:\DB\Zimmersport_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB 
	)
	ALTER DATABASE [Zimmersport] SET COMPATIBILITY_LEVEL = 140
	

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
		EXEC [Zimmersport].[dbo].[sp_fulltext_database] @action = 'enable'
	end
	ALTER DATABASE [Zimmersport] SET ANSI_NULL_DEFAULT OFF 
	ALTER DATABASE [Zimmersport] SET ANSI_NULLS OFF 
	ALTER DATABASE [Zimmersport] SET ANSI_PADDING OFF 
	ALTER DATABASE [Zimmersport] SET ANSI_WARNINGS OFF 
	ALTER DATABASE [Zimmersport] SET ARITHABORT OFF 
	ALTER DATABASE [Zimmersport] SET AUTO_CLOSE OFF 
	ALTER DATABASE [Zimmersport] SET AUTO_SHRINK OFF 
	ALTER DATABASE [Zimmersport] SET AUTO_UPDATE_STATISTICS ON 
	ALTER DATABASE [Zimmersport] SET CURSOR_CLOSE_ON_COMMIT OFF 
	ALTER DATABASE [Zimmersport] SET CURSOR_DEFAULT GLOBAL 
	ALTER DATABASE [Zimmersport] SET CONCAT_NULL_YIELDS_NULL OFF 
	ALTER DATABASE [Zimmersport] SET NUMERIC_ROUNDABORT OFF 
	ALTER DATABASE [Zimmersport] SET QUOTED_IDENTIFIER OFF 
	ALTER DATABASE [Zimmersport] SET RECURSIVE_TRIGGERS OFF 
	ALTER DATABASE [Zimmersport] SET DISABLE_BROKER 
	ALTER DATABASE [Zimmersport] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	ALTER DATABASE [Zimmersport] SET DATE_CORRELATION_OPTIMIZATION OFF 
	ALTER DATABASE [Zimmersport] SET TRUSTWORTHY OFF 
	ALTER DATABASE [Zimmersport] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	ALTER DATABASE [Zimmersport] SET PARAMETERIZATION SIMPLE 
	ALTER DATABASE [Zimmersport] SET READ_COMMITTED_SNAPSHOT OFF 
	ALTER DATABASE [Zimmersport] SET HONOR_BROKER_PRIORITY OFF 
	ALTER DATABASE [Zimmersport] SET RECOVERY FULL 
	ALTER DATABASE [Zimmersport] SET  MULTI_USER 
	ALTER DATABASE [Zimmersport] SET PAGE_VERIFY CHECKSUM  
	ALTER DATABASE [Zimmersport] SET DB_CHAINING OFF 
	ALTER DATABASE [Zimmersport] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	ALTER DATABASE [Zimmersport] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	ALTER DATABASE [Zimmersport] SET DELAYED_DURABILITY = DISABLED 
	ALTER DATABASE [Zimmersport] SET QUERY_STORE = OFF
END
GO

USE [Zimmersport]
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Zimmersport')
BEGIN
	
	ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
	ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
	ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
	ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
	ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
	ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
	ALTER DATABASE [Zimmersport] SET  READ_WRITE 
END
GO
